apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: caddy
  labels:
    app.kubernetes.io/name: caddy-gateway
    app.kubernetes.io/component: operator
    app.kubernetes.io/instance: caddy-system
    app.kubernetes.io/part-of: caddy-system
spec:
  controllerName: caddyserver.com/gateway-controller
