name: Nix

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flake-check:
    name: flake check
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Code checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@8cdf194da984e4f12b2f8c36d1fa107c1dd67f5c # v11

      - name: Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@b46e247b898aa56e6d2d2e728dc6df6c84fdb738 # v7

      - name: nix flake check
        run: nix flake check --all-systems
